### ISSUE TITLE
Ignore conflicts when deploying

### ISSUE THREAD

**Issue by lechum2** [jonathanmorris180/salesforce.nvim#18]
## Describe the problem

There is a configuration option for file manager to ignore conflicts. This option adds --ignore-conflicts flag for `sf project retrieve` command. I would also like to have that same option for `sf project deploy` command.

## Describe the solution

Option 1 would be to utilise the same configuration option and just add `--ignore-conflicts` flag to the deploy command in the same way as it is done for retrieve command.

Option 2 might be to change the setting and have a separate one for retrieval and deployment. Than use those settings when adding a flag to retrieve and deploy commands respectively.

**Comment by lechum2** [comment]
Personally I use git as the source of truth for my orgs and I don't care for conflicts with what is on sandboxes. Option 1 would work for me.

**Comment by jonathanmorris180** [comment]
@lechum2 Apologies for the delay with this, things have been busy! #21 resolves this issue—I just went the simple route and kept the configuration the same to avoid breaking changes. `--ignore-conflicts` is now added to both commands when the config option is set to `true`.

**Comment by lechum2** [comment]
@jonathanmorris180 you've got nothing to apologize for! Thank you for the change, and all your work on the extension!
