### ISSUE TITLE
Cannot select default org

### ISSUE THREAD

**Issue by sahilkmishra** [jonathanmorris180/salesforce.nvim#25]
## Description

E5108: Error executing lua ...nvim/lazy/salesforce.nvim/lua/salesforce/org_manager.lua:128: attempt to concatenate local 'org_alias' (a nil value)
stack traceback:
	...nvim/lazy/salesforce.nvim/lua/salesforce/org_manager.lua:128: in function 'select_org'
	[string ":lua"]:1: in main chunk

## Steps to reproduce

1. I did SalesforceSetDefaultOrg
2. ![image](https://github.com/jonathanmorris180/salesforce.nvim/assets/3820242/870b847d-a010-4697-b527-8f74927dbf74)
3. tried to hit enter on line 3 
4. Error

## Expected behavior

Set the default org or give me a hint? I figure this has to do with the alias being nil but unsure 

## Environment

- Neovim version: Nightly(10.x)
- salesforce.nvim version: latest 
- Plugin clash: NA
- Ubuntu 23.10

**Comment by sahilkmishra** [comment]
This was fixed by adding an alias, but imo would be nice to see nil allow you to set alias or at least point to sfdx set alias

**Comment by jonathanmorris180** [comment]
Thanks for opening @sahilkmishra, I'll fix this in the next release.
